[game]
hostname = "[EN] ðŸŒ³ | Parkstation"
desc = "An English MRP server focused on higher RP expectations and calmer rounds."
maxplayers = 48
soft_max_players = 32
lobbyenabled = true
lobbyduration = 180
role_timers = true
fallbackpreset = "extended"
map_pool = "ParkMapPool"
# loadouts_enabled = true
# loadouts_points = 14

[npc]
enabled = true
pathfinding = true

[server]
rules_file = "ParkRules"
id = "parkstation"

[whitelist]
enabled = true
# min_players = 24

[queue]
enabled = true

# [events]
# ramping_average_end_time = 120.0
# ramping_average_chaos = 7.0


[shuttle]
emergency_early_launch_allowed = true
emergency_dock_time = 260.0
emergency_transit_time_min = 120.0
emergency_transit_time_max = 240.0
recall_turning_point = 0.75
auto_call_time = 150
arrivals = false

[explosion]
tiles_per_tick = 128
incremental_tile = false

[ic]
restricted_names = false
flavor_text = true

[ooc]
enable_during_round = true

[vote]
map_enabled = true
restart_enabled = true
restart_required_ratio = 0.75
restart_not_allowed_when_admin_online = true
timermap = 45


[hub]
tags = "rp:med,region:am_n_e,lang:en,no_tag_infer"

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = true

[net]
tickrate = 30
log_late_msg = false


[infolinks]
discord = "https://discord.gg/49KeKwXc8g"
github = "https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw"
patreon = "https://www.patreon.com/simple14"

[admin]
new_player_join_sound = true


[build]
fork_id = "Parkstation"
